# Generated by Django 4.2 on 2023-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('faculties_required', models.IntegerField()),
                ('faculties_available', models.IntegerField()),
                ('deficiency', models.IntegerField()),
                ('approval_uploaded', models.IntegerField()),
                ('cvs_available', models.CharField(max_length=100)),
                ('interview_scheduled', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
