# Generated by Django 4.2.4 on 2023-09-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'managed': False},
        ),
    ]
