# Generated by Django 4.2.4 on 2023-09-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsapp', '0003_alter_teacherinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'managed': True},
        ),
    ]
