# Generated by Django 4.2.4 on 2023-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsapp', '0004_alter_teacherinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='approval_uploaded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='cvs_available',
            field=models.CharField(blank=True, db_column='CVs_available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='deficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='faculties_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='faculties_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='interview_scheduled',
            field=models.DateField(blank=True, db_column='interview_Scheduled', null=True),
        ),
        migrations.AlterModelTable(
            name='teacherinfo',
            table='Schools_TeacherInfo',
        ),
    ]
