# Generated by Django 4.2.4 on 2023-09-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoolfacultymembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, max_length=20, null=True)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('Designation', models.IntegerField()),
                ('School', models.IntegerField(blank=True, null=True)),
                ('Group', models.IntegerField()),
            ],
            options={
                'db_table': 'elmtschool_TeacherInfo',
                'managed': True,
            },
        ),
    ]
